appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: gOY/NqnG3dyGXwfuizcpb47EE2FYC+6CSlUehYbBrzxmhmtdJlfz1oWuBNG+mGeNBilR0tV1Nde4yzjnJZSJAwyZOc8yOgn7NOL4NKthJjJrLKgVGNFw573ADv2Sy61CL0YzrzU8Y0b8kvZRUiuxshaH4P2LmgrMSUzRS+OIXX8ExYa1Uz7iQdRr2u0BBANm4MTty/kfp68fcgR/A0zNvLG0ENwhRQutW3s4ojVo4NllFHD/BLfDIX0/HZ94UouX9hNTgbOA+8HDxQc5DBV5lyL5ab4frVGcYp2FUCgK62F/pXzCreoVBzP9zaKRvVk9vr2gKhQH8MmiKCsZN25/sfRf/IQ2YUKwcgWZ2QDb6wn2EO0WRY5fRINbz6LeQERc8pJt5G5jRdpe+H0NGSb7Sq/JCn12Glh9NPQICxYMFYpHsTtB2P4pruL8IYNEZmQ3wxPC9FHBdLHTu7ug9o6/V4VjMn19Fq7On96moJmMWW1l5j8wKA3IODIVh0q4saadljyl76cKlrsFIQmBF65twqjoYkb8LObPX7dhL84qupWSl8qsETpPvE6gkvpnojDTS24px9ohZTPOqfaHcQ0LrtN9Pf7KWIXGGVedXL49vyrMNO1Q2eN+o2guWTV4pv6m4LZKOWvk+tArZbkm1VuQv/JsKw5XzphGznTHli/6l2Y=
conda_forge_output_validation: true
